-- ==================================================
-- SEED DATA: Granular System Permissions
-- ==================================================

INSERT INTO public.permissions (code, module, description) VALUES
('company.read', 'company', 'View company profile details'),
('company.update', 'company', 'Update company profile, logo, and GST settings'),
('users.read', 'users', 'View company employees and member roles'),
('users.create', 'users', 'Invite new team members to company'),
('users.update', 'users', 'Update member roles and status'),
('users.delete', 'users', 'Remove members from company'),
('customers.read', 'customers', 'View customer list and balances'),
('customers.create', 'customers', 'Create new customer profiles'),
('customers.update', 'customers', 'Update customer profile and credit limits'),
('customers.delete', 'customers', 'Delete customer records'),
('suppliers.read', 'suppliers', 'View supplier list and payable balances'),
('suppliers.create', 'suppliers', 'Create new supplier profiles'),
('suppliers.update', 'suppliers', 'Update supplier profile'),
('suppliers.delete', 'suppliers', 'Delete supplier records'),
('products.read', 'products', 'View product catalog and prices'),
('products.create', 'products', 'Add new products and services'),
('products.update', 'products', 'Edit product prices, SKU, HSN codes'),
('products.delete', 'products', 'Remove products from catalog'),
('inventory.read', 'inventory', 'View stock levels and transaction logs'),
('inventory.create', 'inventory', 'Record stock opening and manual adjustments'),
('inventory.update', 'inventory', 'Adjust inventory stock counts'),
('sales.read', 'sales', 'View sales history and metrics'),
('sales.create', 'sales', 'Create sales orders'),
('invoices.read', 'invoices', 'View GST sales invoices'),
('invoices.create', 'invoices', 'Create and issue sales invoices'),
('invoices.update', 'invoices', 'Edit draft sales invoices'),
('invoices.delete', 'invoices', 'Cancel or void sales invoices'),
('purchases.read', 'purchases', 'View purchase orders and vendor bills'),
('purchases.create', 'purchases', 'Create purchase orders'),
('purchases.update', 'purchases', 'Update purchase orders'),
('purchases.delete', 'purchases', 'Cancel purchase orders'),
('reports.read', 'reports', 'Generate and view GST and financial reports'),
('payments.read', 'payments', 'View payment transaction history'),
('payments.create', 'payments', 'Record payments for invoices and bills'),
('subscriptions.read', 'subscriptions', 'View subscription plan details'),
('subscriptions.manage', 'subscriptions', 'Upgrade, downgrade, or cancel subscription'),
('settings.read', 'settings', 'View system settings'),
('settings.update', 'settings', 'Update system settings'),
('audit_logs.read', 'audit_logs', 'View security audit logs')
ON CONFLICT (code) DO NOTHING;
